name: Atualizar estatísticas do README

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-cards:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v6

      - name: Gerar cartão de linguagens
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: "username=pietro-ramos&layout=donut&langs_count=8&size_weight=0.5&count_weight=0.5&bg_color=353D41&border_color=123547&title_color=EB9326&text_color=FFFFFF&locale=pt-br"
          path: profile/top-langs.svg
          token: ${{ secrets.GH_STATS_TOKEN }}
          fail_on_error: true

      - name: Gerar cartão de estatísticas
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: "username=pietro-ramos&show_icons=true&include_all_commits=true&hide_title=true&hide=stars&rank_icon=github&bg_color=353D41&border_color=123547&icon_color=EB9326&title_color=EB9326&text_color=FFFFFF&locale=pt-br"
          path: profile/github-stats.svg
          token: ${{ secrets.GH_STATS_TOKEN }}
          fail_on_error: true

      - name: Salvar cartões
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Atualiza cartões de estatísticas" || exit 0
          git push
